/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AnalysisReport {
  reportId: string;
  repoUrl: string;
  riskScore: number;
  summary: string;
  dependencies: {
    findings?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  secrets: {
    findings?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  sast: {
    findings?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  iac: {
    findings?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  ciCdSecurity?: {
    findings?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  supplyChainPosture?: {
    checks?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  repoHygiene?: {
    healthPercentage?: number;
    missingFiles?: string[];
    [k: string]: unknown;
  };
  sbom?: {
    format?: string;
    componentCount?: number;
    ref?: string;
    [k: string]: unknown;
  };
  licenseReport?: {
    findings?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  meta: {
    partial?: boolean;
    nodeErrors?: {
      [k: string]: string;
    };
    [k: string]: unknown;
  };
  generatedAt: string;
  [k: string]: unknown;
}
